server:
  port: 1210
  servlet:
    session:
      timeout: 30M
  tomcat:
    min-spare-threads: 5
    max-threads: 300
    uri-encoding: utf-8

spring:
  application:
    name: sagiri
  profiles:
    active: default
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sagiri?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
  thymeleaf:
    mode: HTML5
    cache: false
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  jackson:
    serialization:
      write-dates-as-timestamps: true
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    password: 123456

logging:
  config: classpath:logback-spring.xml
  home: /tmp/logs/
  level:
    root: info
    sagiri.persistence.mapper: debug
    sagiri.persistence.mapper.DomainInfoMapper.insertSelective: info
    sagiri.persistence.mapper.DomainInfoMapper.updateByPrimaryKeySelective: info

mybatis:
  configuration:
    map-underscore-to-camel-case: true

artoria:
  event:
    enabled: false
    destination: EVENT_RECORD
    visitor-id-property-name: visitorId
    client-app-id-property-name: clientAppId
    trace: true
    show-trace-record: true
    send-trace-record: true
  exception:
    enabled: true
    showErrorMessage: true
    defaultServerErrorMessage: 服务器繁忙！
  user:
    enabled: false
    token-expire: 259200000
    exclude-path-patterns:
      - /api/**
  lock:
    enabled: false



